export const UPDATE_IN_GAME_STATS = "UPDATE_IN_GAME_STATS";
export const TRACK_LAST_CLICKED_STAT = "TRACK_LAST_CLICKED_STAT";
export const END_GAME = "END_GAME";
export const START_GAME = "START_GAME";
export const START_FACEBOOK_SESSION = "START_FACEBOOK_SESSION,";
export const GET_USER_SESSION = "GET_USER_SESSION";
export const GET_GAMES = "GET_GAMES";
